### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by valext** [ShawnZeng1996/Memory#2]
分类界面php文件
<div class="right-box">
					<h3 class="article-author"><?php the_author(); ?>
				 		<i class="fa fa-ellipsis-h"></i>
会导致分类界面上无法正常显示蓝色小对勾
应修改为<h3 class="article-author"><?php the_author(); ?>
				 		<i class="fa fa-check-circle"></i>

**Comment by ShawnZeng1996** [comment]
“应修改为”后面咋没了？……我有空看下，感谢！

**Comment by valext** [comment]
fa fa-check-circle

**Comment by ShawnZeng1996** [comment]
好的，感谢反馈

**Comment by ShawnZeng1996** [comment]
这段时间会再抽空改善下免费版
